server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:./data/filedb
    driver-class-name: org.h2.Driver
    hikari:
      username: sa
      password:
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html